/**
 * Anonymized fixture data for Storybook stories. No real hostnames, tokens, or
 * home directories — paths use `/Users/demo/project` style placeholders.
 */
import type {
  ContextSessionsResponse,
  Health,
  IndexHealth,
  MCPTier,
  MemoryData,
  SettingsData,
  Stats,
  WeeklyDigest,
} from '../api/types'

export const fixtureHealth: Health = {
  EmbedderState: 'healthy',
  EmbedderError: '',
  EmbedderLast: '2026-07-28T12:00:00Z',
  EmbedBackend: 'onnx',
  QueueWorkers: 8,
  QueueWorkersEffective: 8,
  QueueWorkersLive: 8,
  QueueThroughput: 12.4,
  QueueQueued: 14,
  QueuePending: 3,
  QueuePendingPeak: 40,
  QueueInFlight: 2,
  QueueHighCap: 128,
  QueueLowCap: 2048,
  CacheHitRatio: 0.82,
  HeapMB: 412,
  CPUPercent: 18,
  Uptime: 3 * 3600 * 1e9,
  Version: '3.4.0',
  AbnormalPreviousRun: false,
}

export const fixtureStats: Stats = {
  TotalQueries: 4820,
  TodayQueries: 186,
  TokensSaved: 1_820_000,
  TodayTokens: 94_500,
  DedupTokensSaved: 210_000,
  SavingsVsFiles: 640_000,
  AvgDurationMs: 42.3,
  TodayAvgDurationMs: 38.1,
  TotalChars: 5_240_000,
  VirtualFlushed30d: 12,
  Sessions: 96,
  TodaySessions: 7,
  VirtualInventoryTokens: 18_400,
  VirtualNotesCount: 23,
  VirtualUtilPct30d: 64,
  VirtualOrphanCount: 2,
  VirtualStored30d: 340,
  VirtualAccessed30d: 218,
  VirtualTodayStored: 6,
  VirtualTodayAccessed: 4,
  VirtualMaxNotesGlobal: 500,
  VirtualMaxTokensGlobal: 200_000,
  KvRepairArchivesActive: 1,
  KvRepairRepairsTotal30d: 5,
  KvRepairUtilPct30d: 12,
  ApproxBaselineTokens: 2_540_000,
  ApproxTokensReturned: 720_000,
  ApproxRoundsAvoided: 455.5,
  HeuristicApproximate: true,
  HeuristicLabel: 'approximate',
}

export const fixtureWeeklyDigest: WeeklyDigest = {
  WindowDays: 7,
  TokensSaved: 412_000,
  Queries: 1_120,
  VirtualStored: 84,
  VirtualAccessed: 52,
  TopTools: [
    { ToolName: 'get_context_capsule', Calls: 340, TokensSaved: 180_000, AvgDurationMs: 34.2 },
    { ToolName: 'get_file_context', Calls: 210, TokensSaved: 96_000, AvgDurationMs: 21.8 },
    { ToolName: 'search_semantic', Calls: 150, TokensSaved: 74_000, AvgDurationMs: 45.5 },
  ],
  EmbedReliability: {
    PendingFailures: 0,
    LastAutoRecoverUnix: 1_753_500_000,
    AbnormalPreviousRun: false,
    Available: true,
  },
  Heuristic: {
    ApproxBaselineTokens: 560_000,
    ApproxTokensReturned: 148_000,
    ApproxTokensSaved: 412_000,
    ApproxRoundsAvoided: 103,
    HeuristicApproximate: true,
    HeuristicLabel: 'approximate',
    WindowDays: 7,
  },
}

export const fixtureContextSessions: ContextSessionsResponse = {
  WindowDays: 30,
  Sessions: [
    {
      SessionID: 'sess-a1b2c3d4',
      ProjectPath: '/Users/demo/project',
      NotesCount: 6,
      VirtualTokensStored: 4_200,
      VirtualTokensAccessed: 3_100,
      ActiveNotes: 3,
      ActiveTokens: 2_400,
      FetchedAfterStore: true,
      LastStoreAt: '2026-07-27T18:20:00Z',
      LastAccessAt: '2026-07-28T09:05:00Z',
    },
    {
      SessionID: 'sess-e5f6a7b8',
      ProjectPath: '/Users/demo/another-app',
      NotesCount: 2,
      VirtualTokensStored: 900,
      VirtualTokensAccessed: 0,
      ActiveNotes: 2,
      ActiveTokens: 900,
      FetchedAfterStore: false,
      LastStoreAt: '2026-07-26T14:10:00Z',
    },
  ],
}

export const fixtureIndexHealth: IndexHealth = {
  TotalSymbols: 48_320,
  TotalFiles: 1_240,
  TotalEdges: 15_800,
  TotalVectors: 46_900,
  VectorMemMB: 210,
  MemoryMB: 640,
  DiskMB: 1_820,
  WalMB: 12,
  WalSize: '12 MB',
  CPUPercent: 14,
  HeapMB: 412,
  LoadAvgAvailable: true,
  LoadAvg1: 1.2,
  LoadAvg5: 1.5,
  LoadAvg15: 1.1,
  DiskSize: '512 GB',
  DiskReadMBps: 4.2,
  DiskWriteMBps: 1.8,
  SSDModel: 'Demo NVMe SSD',
  SSDSmartStatus: 'PASSED',
  SSDProtocol: 'NVMe',
  SSDCapacity: '512 GB',
  SSDSolidState: true,
  SSDTrim: true,
  SSDAvailable: true,
  SSDWearUsedPct: 3,
  SSDSparePct: 100,
  SSDDataWrittenTB: 2.1,
  SSDTemperatureC: 38,
  EmbedQueued: 14,
  EmbedPending: 3,
  EmbedPendingPeak: 40,
  EmbedFailed: 0,
  EmbedHighQueued: 4,
  EmbedLowQueued: 10,
  EmbedHighCap: 128,
  EmbedLowCap: 2048,
  EmbedActive: 2,
  EmbedActivePrimary: 2,
  EmbedAuxActive: 0,
  EmbedWorkers: 8,
  EmbedWorkersEffective: 8,
  EmbedWorkersLive: 8,
  EmbedWorkerMax: 15,
  EmbedAuxWorkers: 2,
  EmbedAuxWorkersEffective: 2,
  EmbedAuxWorkersLive: 2,
  EmbedAuxWorkerMax: 10,
  EmbedAuxBackend: 'ollama',
  EmbedAuxModel: 'nomic-embed-text',
  EmbedAuxEnabled: true,
  EmbedComplete: 46_900,
  EmbedThroughput: 12.4,
  PinnedCount: 2,
  FilteredProject: '',
  EmbedBackend: 'onnx',
  EmbedModel: 'bge-small-en-v1.5',
  EmbedRuntime: 'onnxruntime',
  EmbedEndpoint: '',
  EmbedDim: 384,
  EmbedderState: 'healthy',
  EmbedderError: '',
  EmbedLoaded: true,
  EmbedRecent: [
    { File: 'internal/dashboard/server.go', ProjectPath: '/Users/demo/project' },
    { File: 'ui/src/App.tsx', ProjectPath: '/Users/demo/project' },
    { File: 'pkg/index/watcher.go', ProjectPath: '/Users/demo/another-app' },
  ],
  EmbedInProgress: [
    { File: 'internal/dashboard/handlers.go', ProjectPath: '/Users/demo/project', Pool: 'primary' },
    { File: 'pkg/embed/onnx.go', ProjectPath: '/Users/demo/another-app', Pool: 'aux' },
  ],
  EmbedConfiguredBackend: 'onnx',
  EmbedConfiguredModel: 'bge-small-en-v1.5',
  EmbedInSync: true,
  WALMaintenanceActive: false,
  LastAutoRecoverUnix: 0,
  Watchers: [
    {
      ProjectPath: '/Users/demo/project',
      Name: 'project',
      Label: 'demo-project',
      Workspace: '/Users/demo/project',
      Active: true,
      LinkedCount: 1,
    },
    {
      ProjectPath: '/Users/demo/another-app',
      Name: 'another-app',
      Label: 'another-app',
      Workspace: '/Users/demo/another-app',
      Active: true,
      LinkedCount: 0,
    },
  ],
}

export const fixtureIndexHealthDegraded: IndexHealth = {
  ...fixtureIndexHealth,
  EmbedderState: 'degraded',
  EmbedderError: 'onnx runtime: probe timeout after 5s (3 consecutive failures)',
  EmbedLoaded: false,
  EmbedThroughput: 0,
  EmbedActive: 0,
  EmbedActivePrimary: 0,
  EmbedAuxActive: 3,
  EmbedQueued: 260,
  EmbedPending: 340,
  EmbedPendingPeak: 340,
  EmbedFailed: 12,
  EmbedInSync: false,
  EmbedInProgress: [
    { File: 'pkg/embed/ollama.go', ProjectPath: '/Users/demo/another-app', Pool: 'aux' },
  ],
  EmbedRecent: [],
  LastAutoRecoverUnix: 1_753_490_000,
}

export const fixtureMemory: MemoryData = {
  TotalSymbols: 48_320,
  TotalVectors: 46_900,
  VectorMemMB: 210,
  VirtualInventoryTokens: 18_400,
  VirtualNotesCount: 23,
  VirtualUtilPct30d: 64,
  VirtualOrphanCount: 2,
  VirtualStored30d: 340,
  VirtualAccessed30d: 218,
  DocSources: [
    { ID: 1, Name: 'React', Type: 'markdown', URL: 'https://react.dev/reference', Age: '2d', Stale: false, Refreshing: false },
    { ID: 2, Name: 'Go stdlib', Type: 'html', URL: 'https://pkg.go.dev/std', Age: '9d', Stale: true, Refreshing: false },
    { ID: 3, Name: 'MUI', Type: 'webpage', URL: 'https://mui.com/material-ui/', Age: '1h', Stale: false, Refreshing: true },
  ],
  DocSourcesTotal: 3,
  DocSourcesPage: 1,
  DocSourcesPerPage: 20,
}

export const fixtureMemoryEmptyDocs: MemoryData = {
  ...fixtureMemory,
  DocSources: [],
  DocSourcesTotal: 0,
}

export const fixtureSettings: SettingsData = {
  IdleUnloadMinutes: 30,
  EmbedWorkerMax: 15,
  EmbedAuxWorkerMax: 10,
  EmbedAuxWorkers: 2,
  EmbedAuxBackend: 'ollama',
  EmbedProbeIntervalSec: 30,
  WatcherIgnoreGlobs: '["**/node_modules/**","**/.git/**","**/dist/**"]',
  ProjectExcludePaths: '',
  IndexLogFiles: false,
  LogRetentionEnabled: true,
  LogRetentionRoots: '/Users/demo/project/logs',
  LogRetentionMaxAgeDays: 14,
  LogRetentionMaxTotalMB: 500,
  LogRetentionDryRun: false,
  QueryRetentionEnabled: true,
  QueryRetentionMaxAgeDays: 30,
  ContextMaxNotesSession: 50,
  ContextMaxTokensSession: 32_000,
  ContextMaxNotesGlobal: 500,
  ContextMaxTokensGlobal: 200_000,
  ContextLimitPolicy: 'lru_session',
  EmbedBackend: 'onnx',
  EmbedModelDir: '',
  EmbedHTTPURL: '',
  EmbedHTTPBearer: '',
  EmbedOllamaHost: 'http://localhost:11434',
  EmbedOllamaModel: 'nomic-embed-text',
  EmbedOpenAIBaseURL: '',
  EmbedOpenAIAPIKey: '',
  EmbedOpenAIModel: '',
  EmbedOpenAIDimensions: '',
  EmbedDockerURL: '',
  EmbedDockerModel: '',
  EmbedActiveBackend: 'onnx',
  EmbedActiveModel: 'bge-small-en-v1.5',
  EmbedInSync: true,
  EmbedderState: 'healthy',
  EmbedderError: '',
  Projects: [
    {
      Path: '/Users/demo/project',
      Label: 'demo-project',
      Name: 'demo-project',
      QueryCount: 4820,
      SymbolCount: 48_320,
      FileCount: 1_240,
      Pinned: true,
      LinkedChildren: [],
      LinkedParent: '',
    },
    {
      Path: '/Users/demo/another-app',
      Label: 'another-app',
      Name: 'another-app',
      QueryCount: 320,
      SymbolCount: 5_100,
      FileCount: 180,
      Pinned: false,
      LinkedChildren: [],
      LinkedParent: '',
    },
  ],
  ProjectsLoading: false,
  Agents: [
    {
      Type: 'cursor',
      Name: 'Cursor',
      Description: 'MCP config + project skills for Cursor IDE',
      GlobalPath: '~/.cursor/mcp.json',
      ProjectPath: '.cursor/mcp.json',
      GlobalInstalled: true,
      ProjectInstalled: true,
    },
    {
      Type: 'claude',
      Name: 'Claude Code',
      Description: 'MCP config for Claude Code CLI',
      GlobalPath: '~/.claude/mcp.json',
      ProjectPath: '.claude/mcp.json',
      GlobalInstalled: false,
      ProjectInstalled: false,
    },
  ],
}

export const fixtureMcpTier: MCPTier = {
  tier: 'complete',
  tools_json_path: '~/.astcache/tools.json',
  tools_json_exists: true,
}
